# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-16 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_details', '0002_auto_20160315_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_password',
            new_name='employee_salary',
        ),
    ]
